---
# SPDX-License-Identifier: GPL-3.0-or-later
# (c) 2020-2024 Peter Mosmans [Go Forward]
#
# Lints a Dockerfile using hadolint.
# Optional configuration will be read from .hadolint.yaml
#
# Variables:
# HADOLINT_VERSION   Specifies which version of hadolint/hadolint is being used

hadolint:
  extends: .sast
  image:
    name: hadolint/hadolint:${HADOLINT_VERSION}
  before_script:
    - mkdir -p reports &>/dev/null || true
  variables:
    GIT_STRATEGY: fetch
  script:
    - >
      hadolint --no-fail Dockerfile > reports/hadolint-report.txt ;
      hadolint --failure-threshold warning -f sonarqube Dockerfile > reports/hadolint-report.json
  # Always show report
  after_script:
    - cat reports/hadolint-report.txt
  artifacts:
    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    when: always
    paths:
      - reports/hadolint-report.*
  # Only flag the job as failed, not the whole pipeline
  allow_failure: true
